### ISSUE TITLE
java.lang.ClassCastException when adding false

### ISSUE THREAD

**Issue by McDjuady** [DPOH-VAR/PowerNBT#11]
When you try to save a NBTCompound containing a boolean value of 'false' a java.lang.ClassCastException will be thrown. This only happens with false but not with true
He is the error:
```
[12:13:08 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'nbttest' in plugin NBTTest v1.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-d97e08b-880a532]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-d97e08b-880a532]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at me.dpohvar.powernbt.utils.ReflectionUtils$RefMethod$RefExecutor.call(ReflectionUtils.java:666) ~[?:?]
        at me.dpohvar.powernbt.utils.NBTUtils_Bukkit_raw.cloneTag(NBTUtils_Bukkit_raw.java:188) ~[?:?]
        at me.dpohvar.powernbt.api.NBTCompound.getHandleCopy(NBTCompound.java:108) ~[?:?]
        at me.dpohvar.powernbt.api.NBTManager.write(NBTManager.java:145) ~[?:?]
        at com.googlemail.mcdjuady.nbttest.NBTTest.onCommand(NBTTest.java:35) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        ... 15 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
        at me.dpohvar.powernbt.utils.ReflectionUtils$RefMethod$RefExecutor.call(ReflectionUtils.java:664) ~[?:?]
        at me.dpohvar.powernbt.utils.NBTUtils_Bukkit_raw.cloneTag(NBTUtils_Bukkit_raw.java:188) ~[?:?]
        at me.dpohvar.powernbt.api.NBTCompound.getHandleCopy(NBTCompound.java:108) ~[?:?]
        at me.dpohvar.powernbt.api.NBTManager.write(NBTManager.java:145) ~[?:?]
        at com.googlemail.mcdjuady.nbttest.NBTTest.onCommand(NBTTest.java:35) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        ... 15 more
Caused by: java.lang.ClassCastException: java.lang.Byte cannot be cast to net.minecraft.server.v1_8_R3.NBTBase
        at net.minecraft.server.v1_8_R3.NBTTagCompound.clone(SourceFile:364) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.NBTTagCompound.clone(SourceFile:364) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
        at me.dpohvar.powernbt.utils.ReflectionUtils$RefMethod$RefExecutor.call(ReflectionUtils.java:664) ~[?:?]
        at me.dpohvar.powernbt.utils.NBTUtils_Bukkit_raw.cloneTag(NBTUtils_Bukkit_raw.java:188) ~[?:?]
        at me.dpohvar.powernbt.api.NBTCompound.getHandleCopy(NBTCompound.java:108) ~[?:?]
        at me.dpohvar.powernbt.api.NBTManager.write(NBTManager.java:145) ~[?:?]
        at com.googlemail.mcdjuady.nbttest.NBTTest.onCommand(NBTTest.java:35) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        ... 15 more
```

This error is reproducable so i wrote a small plugin to test it: https://github.com/McDjuady/NBTTest
Simply execute /nbttest while holding an item in hand

**Comment by DPOH-VAR** [comment]
Thanks!
