### ISSUE TITLE
NPE in me.dpohvar.powernbt.utils.ReflectionUtils

### ISSUE THREAD

**Issue by egg82** [DPOH-VAR/PowerNBT#27]
Quick bug report on an NPE

```[20:32:42 WARN]: copy item meta
java.lang.RuntimeException: java.lang.NullPointerException
        at me.dpohvar.powernbt.utils.ReflectionUtils$RefField$RefExecutor.get(ReflectionUtils.java:802) ~[?:?]
        at me.dpohvar.powernbt.utils.ItemStackUtils.getTag(ItemStackUtils.java:86) ~[?:?]
        at me.dpohvar.powernbt.utils.ItemStackUtils.getTagCB(ItemStackUtils.java:194) ~[?:?]
        at me.dpohvar.powernbt.utils.ItemStackUtils.getTagOrigin(ItemStackUtils.java:217) ~[?:?]
        at me.dpohvar.powernbt.utils.ItemStackUtils.getTag(ItemStackUtils.java:142) ~[?:?]
        at me.dpohvar.powernbt.api.NBTManager.read(NBTManager.java:107) ~[?:?]
        at me.egg82.tcpp.lib.ninja.egg82.nbt.core.PowerNBTCompound.readCompound(PowerNBTCompound.java:300) ~[?:?]
        at me.egg82.tcpp.lib.ninja.egg82.nbt.core.PowerNBTCompound.hasTag(PowerNBTCompound.java:52) ~[?:?]
        at me.egg82.tcpp.events.inventory.inventoryClick.AttachEventCommand.onExecute(AttachEventCommand.java:119) ~[?:?]
        at me.egg82.tcpp.lib.ninja.egg82.patterns.SynchronousCommand.start(SynchronousCommand.java:40) ~[?:?]
        at me.egg82.tcpp.lib.ninja.egg82.plugin.reflection.event.AbstractEventListener.onAnyEvent(AbstractEventListener.java:154) ~[?:?]
        at me.egg82.tcpp.lib.ninja.egg82.plugin.reflection.event.EventListener_1_12.onInventoryClick(EventListener_1_12.java:340) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor231.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[paperclip-1.12.2.jar:git-Paper-1345]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[paperclip-1.12.2.jar:git-Paper-1345]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paperclip-1.12.2.jar:git-Paper-1345]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[paperclip-1.12.2.jar:git-Paper-1345]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[paperclip-1.12.2.jar:git-Paper-1345]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1981) ~[paperclip-1.12.2.jar:git-Paper-1345]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[paperclip-1.12.2.jar:git-Paper-1345]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[paperclip-1.12.2.jar:git-Paper-1345]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[paperclip-1.12.2.jar:git-Paper-1345]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [paperclip-1.12.2.jar:git-Paper-1345]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [paperclip-1.12.2.jar:git-Paper-1345]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [paperclip-1.12.2.jar:git-Paper-1345]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [paperclip-1.12.2.jar:git-Paper-1345]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [paperclip-1.12.2.jar:git-Paper-1345]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NullPointerException```

Server version: Paper 1.12.2

**Comment by MRtecno98** [comment]
I'm also getting this error

**Comment by dpohvar** [comment]
fixed for bukkit api 1.17+
