### ISSUE TITLE
Cannot use hand (or most other commands) on 1.18.2

### ISSUE THREAD

**Issue by paradox460** [DPOH-VAR/PowerNBT#44]
Upon using command `/nbt h`, after a `/nbt debug` call, I see the following in my server's console:

```
[00:57:55 WARN]: [PowerNBT] Exception on command: nbt
java.lang.NoClassDefFoundError: Could not initialize class me.dpohvar.powernbt.api.NBTManager
        at me.dpohvar.powernbt.nbt.NBTContainerEntity.readTag(NBTContainerEntity.java:40) ~[PowerNBT.jar:?]
        at me.dpohvar.powernbt.nbt.NBTContainerEntity.readTag(NBTContainerEntity.java:15) ~[PowerNBT.jar:?]
        at me.dpohvar.powernbt.nbt.NBTContainer.getCustomTag(NBTContainer.java:124) ~[PowerNBT.jar:?]
        at me.dpohvar.powernbt.command.action.Argument.getContainer(Argument.java:377) ~[PowerNBT.jar:?]
        at me.dpohvar.powernbt.command.action.Argument.<init>(Argument.java:79) ~[PowerNBT.jar:?]
        at me.dpohvar.powernbt.command.action.ActionView.<init>(ActionView.java:15) ~[PowerNBT.jar:?]
        at me.dpohvar.powernbt.command.action.ActionView.<init>(ActionView.java:19) ~[PowerNBT.jar:?]
        at me.dpohvar.powernbt.command.CommandNBT.command(CommandNBT.java:71) ~[PowerNBT.jar:?]
        at me.dpohvar.powernbt.command.Command.onCommand(Command.java:30) ~[PowerNBT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.18.2.jar:git-Paper-351]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2306) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2117) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2098) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-351]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-351]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-351]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-351]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-351]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1347) ~[paper-1.18.2.jar:git-Paper-351]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[paper-1.18.2.jar:git-Paper-351]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-351]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Upon using `/nbt block` and targeting a mob spawner, I get the following error:

```
[00:59:06 WARN]: [PowerNBT] Exception on command: nbt
java.lang.NoClassDefFoundError: Could not initialize class me.dpohvar.powernbt.api.NBTManager
        at me.dpohvar.powernbt.nbt.NBTContainerBlock.readTag(NBTContainerBlock.java:51) ~[PowerNBT.jar:?]
        at me.dpohvar.powernbt.nbt.NBTContainerBlock.readTag(NBTContainerBlock.java:17) ~[PowerNBT.jar:?]
        at me.dpohvar.powernbt.nbt.NBTContainer.getCustomTag(NBTContainer.java:124) ~[PowerNBT.jar:?]
        at me.dpohvar.powernbt.nbt.NBTContainer.getCustomTag(NBTContainer.java:138) ~[PowerNBT.jar:?]
        at me.dpohvar.powernbt.utils.Caller.sendValueView(Caller.java:93) ~[PowerNBT.jar:?]
        at me.dpohvar.powernbt.command.action.ActionView.execute(ActionView.java:56) ~[PowerNBT.jar:?]
        at me.dpohvar.powernbt.command.CommandNBT.command(CommandNBT.java:72) ~[PowerNBT.jar:?]
        at me.dpohvar.powernbt.command.Command.onCommand(Command.java:30) ~[PowerNBT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.18.2.jar:git-Paper-351]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2306) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2117) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2098) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-351]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-351]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-351]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-351]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-351]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1347) ~[paper-1.18.2.jar:git-Paper-351]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[paper-1.18.2.jar:git-Paper-351]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-351]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Freemandns** [comment]
### Машинный перевод
Hi, @paradox460 ! I made a pull request ( #45 ) with Minecraft 1.18.2 support for this plugin. If it's difficult for you to compile my version, then I can make a release with .jar file in my repository.

### Original
Привет, @paradox460 ! Я сделал pull request ( #45 ) с поддержкой Minecraft 1.18.2 для этого плагина. Если тебе сложно скомпилировать мою версию, то я могу сделать релиз с .jar файлом в моем репозитории.
